default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :distribute do
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "kslama499@gmail.com",
      release_notes: "Some Features in Live for Think Spark",
  )
  end
end